version: '2.4'
services:

  lb:
    image: dockercloud/haproxy:1.6.7
    links:
      - py3
    ports:
      - 80:80
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  py3:
    build:
      context: ./py3
      dockerfile: ./Dockerfile
    expose:
      - 8080
    restart: always
    scale: 2
    volumes:
      - ./py3/app:/app

  redis:
    image: redis:5-alpine
    # DO NOT save to disk;  DB-count 16 -> 2
    command: ["sh", "-c", "exec redis-server --save \"\" --databases 2 "]
    restart: always

# docker network create app
networks:
  default:
    external:
      name: "app"
